from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="User", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("password", models.CharField(max_length=128, verbose_name="password")), ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")), ("is_superuser", models.BooleanField(default=False)), ("first_name", models.CharField(blank=True, max_length=150)), ("last_name", models.CharField(blank=True, max_length=150)), ("is_staff", models.BooleanField(default=False)), ("is_active", models.BooleanField(default=True)), ("date_joined", models.DateTimeField(default=django.utils.timezone.now)), ("email", models.EmailField(max_length=254, unique=True)), ("display_name", models.CharField(blank=True, max_length=80)), ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=12)), ("approved_at", models.DateTimeField(blank=True, null=True)), ("groups", models.ManyToManyField(blank=True, to="auth.group")), ("user_permissions", models.ManyToManyField(blank=True, to="auth.permission"))]),
        migrations.CreateModel(name="SystemState", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("initial_admin_claimed", models.BooleanField(default=False)), ("scheduler_heartbeat", models.DateTimeField(blank=True, null=True))]),
        migrations.CreateModel(name="Product", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("retailer", models.CharField(default="nintendo_ca", max_length=32)), ("canonical_url", models.URLField(unique=True)), ("external_id", models.CharField(blank=True, max_length=128)), ("title", models.CharField(max_length=255)), ("image_url", models.URLField(blank=True)), ("price", models.CharField(blank=True, max_length=32)), ("availability", models.CharField(choices=[("available", "Available"), ("unavailable", "Unavailable"), ("unknown", "Unknown"), ("error", "Error"), ("blocked", "Blocked")], default="unknown", max_length=16)), ("last_checked_at", models.DateTimeField(blank=True, null=True)), ("last_success_at", models.DateTimeField(blank=True, null=True)), ("last_error", models.CharField(blank=True, max_length=255)), ("next_check_at", models.DateTimeField(blank=True, null=True)), ("updated_at", models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="DiscordWebhook", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80)), ("encrypted_url", models.TextField()), ("enabled", models.BooleanField(default=True)), ("last_tested_at", models.DateTimeField(blank=True, null=True)), ("last_delivery_error", models.CharField(blank=True, max_length=255)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webhooks", to="core.user"))], options={"unique_together": {("owner", "name")}}),
        migrations.CreateModel(name="Validation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("canonical_url", models.URLField()), ("title", models.CharField(max_length=255)), ("image_url", models.URLField(blank=True)), ("price", models.CharField(blank=True, max_length=32)), ("availability", models.CharField(max_length=16)), ("expires_at", models.DateTimeField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user"))]),
        migrations.CreateModel(name="Monitor", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("active", models.BooleanField(default=True)), ("armed", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monitors", to="core.user")), ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monitors", to="core.product")), ("webhook", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="monitors", to="core.discordwebhook"))], options={"unique_together": {("owner", "product")}}),
        migrations.CreateModel(name="CheckResult", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(max_length=16)), ("price", models.CharField(blank=True, max_length=32)), ("error", models.CharField(blank=True, max_length=255)), ("checked_at", models.DateTimeField(auto_now_add=True)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checks", to="core.product"))]),
        migrations.CreateModel(name="NotificationDelivery", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("event_type", models.CharField(default="restock", max_length=32)), ("delivered", models.BooleanField(default=False)), ("error", models.CharField(blank=True, max_length=255)), ("attempted_at", models.DateTimeField(auto_now_add=True)), ("monitor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="core.monitor"))]),
    ]
