# Generated by Django 5.2.17 on 2026-09-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_delivery_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fast_check_intervals_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
